name: firesaftey
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  webview_flutter: ^4.0.0
  intl: ^0.18.1
  percent_indicator: ^4.2.3
  barcode_widget: ^2.0.3
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  http: ^1.2.0
  logger: ^2.5.0
  video_player: ^2.8.2
  google_generative_ai: ^0.3.2
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  fl_chart: ^0.64.0
  flutter_markdown: ^0.6.14
  mime: ^1.0.4

  # ✅ Downgraded to stable version that works with latest Flutter
  file_picker: ^5.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/
